<?php

/**
 * @file
 * Contains migrate_api_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_api_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_api_example module.
    case 'help.page.migrate_api_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate example module') . '</p>';
      return $output;

    default:
  }
}
